// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package render

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	templpkg "github.com/a-h/templ"
	"github.com/araihu/goshtoso/components/codeblock"
	"github.com/araihu/goshtoso/components/combobox"
	"github.com/araihu/manja/domain"
	"strings"
)

func RequestGenerator(operation domain.Operation, serverURL string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section data-manja-request-composer data-manja-request-samples=\"true\" aria-label=\"Request samples\" class=\"grid min-w-0 gap-3\"><h4 class=\"font-title text-lg font-semibold\">Request</h4><div data-manja-request-sample class=\"min-w-0\"><div data-manja-request-sample-target class=\"mb-3 min-w-0\" x-data=\"{}\" x-init=\"$el.querySelectorAll('[data-combobox-option]').forEach(option => option.tabIndex = -1)\" x-on:combobox:change=\"$dispatch('manja-request-sample-target-change', { value: $event.detail.values[0] })\" x-on:input.capture=\"if ($event.target.matches('[data-combobox-search]')) { $event.stopImmediatePropagation(); const query = $event.target.value.trim().toLowerCase(); $el.querySelectorAll('[data-combobox-option]').forEach(option => option.hidden = !option.textContent.toLowerCase().includes(query)); }\" x-on:keydown.capture=\"if (['ArrowDown', 'ArrowUp'].includes($event.key) && $event.target.matches('[data-combobox-search], [data-combobox-option]')) { $event.preventDefault(); $event.stopImmediatePropagation(); const options = [...$el.querySelectorAll('[data-combobox-option]')].filter(option => !option.hidden && option.getAttribute('aria-disabled') !== 'true'); const index = options.indexOf($event.target); const next = index < 0 ? ($event.key === 'ArrowDown' ? 0 : options.length - 1) : (index + ($event.key === 'ArrowDown' ? 1 : -1) + options.length) % options.length; options[next]?.focus(); }\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		cfg := requestGeneratorCombobox(operation.Anchor)
		templ_7745c5c3_Err = combobox.Combobox(cfg, cfg.InitialState()).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = codeblock.CodeBlock(codeblock.Config{ID: operation.Anchor + "-request-sample-code", Label: "Request Sample: Shell / cURL", Language: "shell", Code: requestGeneratorFallback(operation, serverURL), MaxHeight: "24rem"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, parameter := range operation.Parameters {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<input type=\"hidden\" name=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(requestGeneratorParameterField(parameter))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/localdocs/render/request_generator.templ`, Line: 28, Col: 72}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(requestGeneratorParameterValue(parameter))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/localdocs/render/request_generator.templ`, Line: 28, Col: 124}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\"> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if operation.RequestBody != nil && len(operation.RequestBody.MediaTypes) > 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<textarea hidden data-manja-request-body-input>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(operation.RequestBody.MediaTypes[0].Example)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/localdocs/render/request_generator.templ`, Line: 31, Col: 95}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</textarea>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templpkg.JSONScript(operation.Anchor+"-request-composer-payload", requestGeneratorPayload(operation, serverURL)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func requestGeneratorCombobox(anchor string) combobox.Config {
	options := make([]combobox.Option, 0, len(RequestSampleTargets()))
	for _, target := range RequestSampleTargets() {
		options = append(options, combobox.Option{Value: target.Value, Label: target.Label})
	}
	return combobox.Config{
		ID: anchor + "-sample-target", Name: "requestSampleTarget", Label: "Language / tool",
		Mode: combobox.ModeSingle, Source: combobox.Source{Static: options},
		Selected: []string{"shell:curl"}, EnableSearch: true, RootClass: "w-full",
	}
}

func requestGeneratorFallback(operation domain.Operation, serverURL string) string {
	copy := operation
	copy.RequestTarget = strings.TrimRight(serverURL, "/") + domain.EffectiveOperationRequestTarget(operation)
	return operationExamplesCurl(copy)
}

func requestGeneratorParameterField(parameter domain.OperationParameter) string {
	return "parameters." + parameter.In + "." + parameter.Name
}

func requestGeneratorParameterValue(parameter domain.OperationParameter) string {
	if parameter.Example != "" {
		return parameter.Example
	}
	if parameter.In == "path" {
		return "{" + parameter.Name + "}"
	}
	return ""
}

func requestGeneratorPayload(operation domain.Operation, serverURL string) map[string]any {
	parameters := make([]map[string]string, 0, len(operation.Parameters))
	for _, parameter := range operation.Parameters {
		parameters = append(parameters, map[string]string{"name": parameter.Name, "in": parameter.In, "fieldName": requestGeneratorParameterField(parameter)})
	}
	payload := map[string]any{"method": operation.Method, "urlTemplate": strings.TrimRight(serverURL, "/") + domain.EffectiveOperationRequestTarget(operation), "parameters": parameters, "sampleTargets": RequestSampleTargets()}
	if operation.RequestBody != nil && len(operation.RequestBody.MediaTypes) > 0 {
		payload["bodyContentType"] = operation.RequestBody.MediaTypes[0].ContentType
	}
	return payload
}

var _ = templruntime.GeneratedTemplate
