package webassets

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/evanw/esbuild/pkg/api"
)

const generatedHeader = "// Code generated by cmd/webassets; DO NOT EDIT."

const requestComposerEntry = `
import { Buffer } from 'buffer';
import { HTTPSnippet } from '@readme/httpsnippet';
import hljs from 'highlight.js/lib/core';
import bash from 'highlight.js/lib/languages/bash';
import javascript from 'highlight.js/lib/languages/javascript';
import python from 'highlight.js/lib/languages/python';
import go from 'highlight.js/lib/languages/go';
import java from 'highlight.js/lib/languages/java';
import php from 'highlight.js/lib/languages/php';
import ruby from 'highlight.js/lib/languages/ruby';
import csharp from 'highlight.js/lib/languages/csharp';
import powershell from 'highlight.js/lib/languages/powershell';
import swift from 'highlight.js/lib/languages/swift';
import kotlin from 'highlight.js/lib/languages/kotlin';
import json from 'highlight.js/lib/languages/json';
import http from 'highlight.js/lib/languages/http';
import c from 'highlight.js/lib/languages/c';
import clojure from 'highlight.js/lib/languages/clojure';
import objectivec from 'highlight.js/lib/languages/objectivec';
import ocaml from 'highlight.js/lib/languages/ocaml';
import r from 'highlight.js/lib/languages/r';

if (!globalThis.Buffer) {
  globalThis.Buffer = Buffer;
}
Object.entries({
  bash,
  javascript,
  python,
  go,
  java,
  php,
  ruby,
  csharp,
  powershell,
  swift,
  kotlin,
  json,
  http,
  c,
  clojure,
  objectivec,
  ocaml,
  r,
}).forEach(([name, language]) => hljs.registerLanguage(name, language));
globalThis.ManjaHTTPSnippet = { HTTPSnippet };
globalThis.ManjaHighlight = hljs;
`

func Generate(repoRoot string, check bool) (Report, error) {
	artifacts, report, err := buildArtifacts(repoRoot)
	if err != nil {
		return Report{}, err
	}
	paths := make([]string, 0, len(artifacts))
	for relative := range artifacts {
		paths = append(paths, relative)
	}
	sort.Strings(paths)
	var result error
	for _, relative := range paths {
		destination := filepath.Join(repoRoot, filepath.FromSlash(relative))
		if check {
			current, readErr := os.ReadFile(destination)
			if readErr != nil || !bytes.Equal(current, artifacts[relative]) {
				result = errors.Join(result, fmt.Errorf("%s is stale", relative))
			}
			continue
		}
		if err := writeAtomic(destination, artifacts[relative]); err != nil {
			return Report{}, err
		}
	}
	return report, result
}

func buildArtifacts(repoRoot string) (map[string][]byte, Report, error) {
	absoluteRoot, err := filepath.Abs(repoRoot)
	if err != nil {
		return nil, Report{}, err
	}
	repoRoot = absoluteRoot
	bundles, err := LoadRepositoryMetadata(repoRoot)
	if err != nil {
		return nil, Report{}, err
	}
	temporary, err := os.MkdirTemp("", "manja-webassets-")
	if err != nil {
		return nil, Report{}, err
	}
	defer os.RemoveAll(temporary)
	modules, err := Stage(context.Background(), temporary, allPackages(bundles))
	if err != nil {
		return nil, Report{}, err
	}

	schema, schemaReport, err := buildSchemaExample(repoRoot, modules)
	if err != nil {
		return nil, Report{}, err
	}
	composer, composerReport, err := buildRequestComposer(repoRoot, modules)
	if err != nil {
		return nil, Report{}, err
	}
	if err := validateReportPackages(bundles, []BundleReport{schemaReport, composerReport}); err != nil {
		return nil, Report{}, err
	}
	report := Report{Bundles: []BundleReport{composerReport, schemaReport}}
	notices, err := renderNotices(bundles, report)
	if err != nil {
		return nil, Report{}, err
	}
	return map[string][]byte{
		"internal/web/static/schema-example.js":   schema,
		"internal/web/static/request-composer.js": composer,
		"docs/legal/browser-bundles.md":           notices,
	}, report, nil
}

func buildSchemaExample(repoRoot, modules string) ([]byte, BundleReport, error) {
	samplerPath := filepath.Join(modules, "openapi-sampler", "dist", "openapi-sampler.js")
	hydratorPath := filepath.Join(repoRoot, "internal", "web", "static", "schema-example-hydrator.js")
	sampler, err := os.ReadFile(samplerPath)
	if err != nil {
		return nil, BundleReport{}, err
	}
	hydrator, err := os.ReadFile(hydratorPath)
	if err != nil {
		return nil, BundleReport{}, err
	}
	output := joinArtifact(string(sampler), string(hydrator))
	return output, BundleReport{
		Name: "schema-example", Output: "internal/web/static/schema-example.js",
		Inputs:   []string{"internal/web/static/schema-example-hydrator.js", "openapi-sampler/dist/openapi-sampler.js"},
		Packages: []string{"openapi-sampler"},
	}, nil
}

func buildRequestComposer(repoRoot, modules string) ([]byte, BundleReport, error) {
	result := api.Build(api.BuildOptions{
		AbsWorkingDir: repoRoot,
		Stdin:         &api.StdinOptions{Contents: requestComposerEntry, ResolveDir: repoRoot, Sourcefile: "request-composer-vendor.js", Loader: api.LoaderJS},
		NodePaths:     []string{modules}, Bundle: true, Write: false, Metafile: true,
		Format: api.FormatIIFE, Platform: api.PlatformBrowser, Target: api.ES2020,
		MinifyWhitespace: true, MinifySyntax: true, MinifyIdentifiers: true,
		Define: map[string]string{"process.env.NODE_ENV": `"production"`}, LogLevel: api.LogLevelSilent,
	})
	if len(result.Errors) != 0 || len(result.Warnings) != 0 {
		return nil, BundleReport{}, fmt.Errorf("esbuild: %s", formatMessages(append(result.Errors, result.Warnings...)))
	}
	if len(result.OutputFiles) != 1 {
		return nil, BundleReport{}, fmt.Errorf("esbuild output files = %d, want 1", len(result.OutputFiles))
	}
	var metafile struct {
		Inputs map[string]json.RawMessage `json:"inputs"`
	}
	if err := json.Unmarshal([]byte(result.Metafile), &metafile); err != nil {
		return nil, BundleReport{}, err
	}
	inputKeys := make([]string, 0, len(metafile.Inputs))
	for input := range metafile.Inputs {
		inputKeys = append(inputKeys, input)
	}
	inputs, packages, err := normalizeInputs(inputKeys)
	if err != nil {
		return nil, BundleReport{}, err
	}
	inputs = append(inputs, "internal/web/static/request-composer-hydrator.js")
	sort.Strings(inputs)
	hydrator, err := os.ReadFile(filepath.Join(repoRoot, "internal", "web", "static", "request-composer-hydrator.js"))
	if err != nil {
		return nil, BundleReport{}, err
	}
	output := joinArtifact(string(result.OutputFiles[0].Contents), string(hydrator))
	return output, BundleReport{Name: "request-composer", Output: "internal/web/static/request-composer.js", Inputs: inputs, Packages: packages}, nil
}

func validateReportPackages(bundles []Bundle, reports []BundleReport) error {
	declared := make(map[string][]string, len(bundles))
	for _, bundle := range bundles {
		for _, pkg := range bundle.Packages {
			declared[bundle.Name] = append(declared[bundle.Name], pkg.Name)
		}
		sort.Strings(declared[bundle.Name])
	}
	for _, report := range reports {
		if !equalStrings(declared[report.Name], report.Packages) {
			return fmt.Errorf("bundle %q package graph = %v, declared %v", report.Name, report.Packages, declared[report.Name])
		}
	}
	return nil
}

func joinArtifact(vendor, hydrator string) []byte {
	return []byte(generatedHeader + "\n" + stripTrailingWhitespace(vendor) + "\n;\n" + stripTrailingWhitespace(hydrator) + "\n")
}

func stripTrailingWhitespace(value string) string {
	lines := strings.Split(strings.TrimRight(value, "\r\n"), "\n")
	for index := range lines {
		lines[index] = strings.TrimRight(lines[index], " \t\r")
	}
	return strings.Join(lines, "\n")
}

func formatMessages(messages []api.Message) string {
	values := make([]string, 0, len(messages))
	for _, message := range messages {
		values = append(values, message.Text)
	}
	return strings.Join(values, "; ")
}

func writeAtomic(destination string, contents []byte) error {
	if err := os.MkdirAll(filepath.Dir(destination), 0o755); err != nil {
		return err
	}
	file, err := os.CreateTemp(filepath.Dir(destination), ".webassets-output-")
	if err != nil {
		return err
	}
	temporary := file.Name()
	defer os.Remove(temporary)
	if _, err = file.Write(contents); err == nil {
		err = file.Chmod(0o644)
	}
	if err == nil {
		err = file.Sync()
	}
	if closeErr := file.Close(); err == nil {
		err = closeErr
	}
	if err != nil {
		return err
	}
	return os.Rename(temporary, destination)
}

func equalStrings(left, right []string) bool {
	if len(left) != len(right) {
		return false
	}
	for index := range left {
		if left[index] != right[index] {
			return false
		}
	}
	return true
}
