// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/araihu/goshtoso/components/head"

func Layout(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\" data-theme=\"goshtoso\" x-data=\"{\n\t\t\ttheme: localStorage.getItem('theme') || 'goshtoso',\n\t\t\tdarkMode: (function() {\n\t\t\t\tconst stored = localStorage.getItem('darkMode');\n\t\t\t\tif (stored !== null) return stored === 'true';\n\t\t\t\treturn window.matchMedia('(prefers-color-scheme: dark)').matches;\n\t\t\t})(),\n\t\t\tsetTheme(name) { this.theme = name; document.documentElement.setAttribute('data-theme', name); },\n\t\t\tapplyDarkMode(on) { document.documentElement.classList.toggle('dark', on); },\n\t\t\ttoggleDarkMode() { this.darkMode = !this.darkMode; }\n\t\t}\" x-init=\"\n\t\t\tdocument.documentElement.setAttribute('data-theme', theme);\n\t\t\tapplyDarkMode(darkMode);\n\t\t\t$watch('theme', value => {\n\t\t\t\tlocalStorage.setItem('theme', value);\n\t\t\t\tdocument.documentElement.setAttribute('data-theme', value);\n\t\t\t});\n\t\t\t$watch('darkMode', value => {\n\t\t\t\tlocalStorage.setItem('darkMode', value ? 'true' : 'false');\n\t\t\t\tapplyDarkMode(value);\n\t\t\t});\n\t\t\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/layout.templ`, Line: 37, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</title><script>\n\t\t\t\t(function() {\n\t\t\t\t\ttry {\n\t\t\t\t\t\tdocument.documentElement.setAttribute('data-theme', localStorage.getItem('theme') || 'goshtoso');\n\t\t\t\t\t\tvar d = localStorage.getItem('darkMode');\n\t\t\t\t\t\tvar on = d !== null ? d === 'true' : window.matchMedia('(prefers-color-scheme: dark)').matches;\n\t\t\t\t\t\tdocument.documentElement.classList.toggle('dark', on);\n\t\t\t\t\t} catch (e) {}\n\t\t\t\t})();\n\t\t\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = head.Dependencies().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<link rel=\"stylesheet\" href=\"/manja-assets/manja.css\"><style>[x-cloak] { display: none !important; }</style></head><body class=\"min-h-screen bg-surface text-on-surface dark:bg-surface-dark dark:text-on-surface-dark\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
